---
#################################################
#
# This creates applies config to allow oauth through an openid provider
# A vars file needs to be passed at run time with the correct config defined
# This playbook assumes a logged in admin oc user locally
#
#################################################

- hosts: localhost
  name: Idp config setup


  tasks:

    - name: Create secret for openid
      command: /usr/bin/oc create secret generic {{idp_secret_name}} --from-literal=clientSecret={{idp_secret}} -n openshift-config

    - name: Try toGenerate and apply config
      block:
        - name: generate config
          template:
            src: templates/openshift-idp.yml
            dest: templates/openshift-idp-complete.yml

        - name: Apply oauth config
          command: /usr/bin/oc apply -f templates/openshift-idp-complete.yml

      always:
        - name: remove temp config file
          file:
            path: templates/openshift-idp-complete.yml
            state: absent

