---
- hosts: all
  become: True

  tasks:
    - name: Patching grub config
      shell:
        cmd: "grubby --update-kernel=ALL --args='initcall_blacklist=algif_aead_init' && touch /usr/libexec/centos/cve-2026-31431.patched"
        creates: /usr/libexec/centos/cve-2026-31431.patched
      register: cve_2026_31431

    - name: Rebooting host if needed
      reboot:
        msg: "Rebooting for copy-fail cve patch"
      when: cve_2026_31431 is changed
        
