---

# This playbook requires a file provided to it for vars
# An example of the file exists in inventory/group_vars/openshift-ci-stg

# It also assumes that an empty Route53 zone exists

# it creates some files locally which should be pushed to the filestore as
# they contain install info needed for the cluster

- hosts: localhost

  tasks:
    - name: create build directory for deployment artifacts
      file:
        path: "{{ openshift_build_path }}"
        state: directory
        mode: 0700

    - name: download and extract openshift installer
      unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-install-linux.tar.gz
        dest: "{{ openshift_build_path }}"
        remote_src: yes

    - name: create openshift install-config.yaml file
      template:
        src: "install-config.yaml.j2"
        dest: "{{ openshift_build_path }}/install-config.yaml"

    - name: backup install-config.yaml file as install-config.yaml.backup
      copy:
        src: "{{ openshift_build_path }}/install-config.yaml"
        dest: "{{ openshift_build_path }}/install-config.yaml.backup"

    - name: Run the install
      command: "{{ openshift_build_path }}/openshift-install create cluster --dir={{ openshift_build_path }}"
      environment:
        AWS_ACCESS_KEY: "{{openshift_ci_access_key}}"
        AWS_SECRET_ACCESS_KEY: "{{openshift_ci_secret_key}}"
