---
# This playbook is an ad-hoc task used to deploy bare-metal nodes
# It used the following variables, declared through inventory (group/host vars):
#  centos_version: 7 # default centos version deployed
#  arch: x86_64  # default architecture
#  root_pass:  # default root_password on provisioned nodes
#  deploy_host:   # node with ipmitool and pxelinux.cfg configurations
#  ks_url: http://your.node/path/to/ks_dir # where to find the generated kickstarts
#  use_md_raid: True # Default to use md_raid for /dev/sda and /dev/sdb
#  md_raid_level: 1
#  lv_root_size: 10000 # in GB
#  lv_root_expand: False  # do we want to have / to max capacity of the VG ?
#  lv_home_size: 2048 # in GB
#  pxe_bootdev: eth0 # device used as bootdev and first interface configured
#
# Call this adhoc playbook with --limit to deploy host[s]/group
#
- hosts: all
  become: true
  gather_facts: false
  tasks:
    
    - name: == Hardware provisioning == Creating kickstart to provision VM[s]
      template: 
        src: "../templates/kickstarts/centos-{{ centos_version }}-ks.cfg.j2" 
        dest: "/var/www/html/ks/{{ inventory_hostname }}-ks.cfg"
      delegate_to: "{{ deploy_host }}"
      tags:
        - ks

    - name: == Hardware provisioning == Generating the tftp configuration boot file
      template: 
        src: ../templates/pxeboot.j2
        dest: /var/lib/tftpboot/pxelinux.cfg/01-{{ macaddress | lower | replace(":","-") }}
        mode: 0755
      delegate_to: "{{ deploy_host }}"
      tags:
        - pxe

    - name: == Hardware provisioning == Ensuring node is powered off
      command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis power off
      delegate_to: "{{ deploy_host }}"
      tags:
        - ipmi

    - name: == Hardware provisioning == Pausing ...
      pause:
        seconds: 8
      tags:
        - ipmi

    - name: == Hardware provisioning == configuring pxe boot
      command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis bootdev pxe
      delegate_to: "{{ deploy_host }}"
      tags:
        - ipmi

    - name: == Hardware provisioning == Pausing ...
      pause:
        seconds: 2
      
    - name: == Hardware provisioning == Ensuring node is powered on
      command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis power on
      delegate_to: "{{ deploy_host }}"
      tags:
        - ipmi

    - name: == Hardware provisioning == Waiting for host to be reachable
      wait_for: 
        host: "{{ ip }}" 
        port: 22 
        timeout: 1200
      delegate_to: "{{ deploy_host }}"
