---
- hosts: all
  become: True

  tasks:
    - name: Find our public ip
      uri:
        url: http://ipv4.icanhazip.com
        return_content: yes
      register: public_ip
      when: 
        - dnf_use_proxy is defined and not dnf_use_proxy
        - ansible_bios_vendor == 'Amazon EC2'
    - set_fact:
        pub_ip: "{{ public_ip.content | replace('\n', '') }}"
      when: 
        - ansible_bios_vendor == 'Amazon EC2'
        - dnf_use_proxy is defined and not dnf_use_proxy

    - name: Generate initial host_vars/{{ inventory_hostname }} in ../out
      template:
        src: ansible-hostvars.j2
        dest: "{{ out_dir }}/{{ inventory_hostname }}"
      delegate_to: localhost
      become: False
