---
# This playbook is an ad-hoc task used to deploy bare-metal nodes for OCP4
# It used the following variables, declared through inventory (group/host vars):
#  rhcos_version: 4.3.8  # default rhcos version deployed
#  arch: x86_64          # default architecture
#  md-raid-dev:          # mdadm device eg: /dev/md126
#  deploy_host:          # node hosting pxelinux.cfg configurations
#  ipmitool_host:        # node with ipmitool and mgmt vlan access
#  pxe_bootdev: eth0     # device used as bootdev and first interface configured
#  rhcos_install_img_url: # Where to grab rhcos install http://<host>/<path>/rhcos/rhcos-4.3.8-x86_64-metal.x86_64.raw.gz
#  rhcos_ignition_file_url: # where to find ignition file http://<host>/config/rhcos/bootstrap.ign #to be modified based on group or host level, for bootstrap, master, etc
#
# Call this adhoc playbook with --limit to deploy host[s]/group
#
- hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: == Hardware provisioning == Generating the tftp configuration boot file
      template: 
        src: ../templates/ocp_pxeboot.j2
        dest: /var/lib/tftpboot/pxelinux.cfg/01-{{ macaddress | lower | replace(":","-") }}
        mode: 0755
      delegate_to: "{{ deploy_host }}"
      tags:
        - pxe

    - name: == Hardware provisioning == Ensuring node is powered off
      command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis power off
      delegate_to: "{{ ipmitool_host }}"
      tags:
        - ipmi

    - name: == Hardware provisioning == Pausing ...
      pause:
        seconds: 8
      tags:
        - ipmi

    - name: == Hardware provisioning == configuring pxe boot
      command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis bootdev pxe
      delegate_to: "{{ ipmitool_host }}"
      tags:
        - ipmi

    - name: == Hardware provisioning == Pausing ...
      pause:
        seconds: 2
      
    - name: == Hardware provisioning == Ensuring node is powered on
      command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis power on
      delegate_to: "{{ ipmitool_host }}"
      tags:
        - ipmi

    - name: == Hardware provisioning == Waiting for host to be reachable
      wait_for: 
        host: "{{ ip }}" 
        port: 22 
        timeout: 1200
      delegate_to: "{{ deploy_host }}"

    - name: Updating/Adding IP in local CI dns resolver if needed
      shell: "/usr/local/bin/update_dns -n {{ inventory_hostname }} -i {{ ip }}"
      delegate_to: "{{ deploy_host }}"
      when: centos_ci_node is defined and centos_ci_node
      tags:
        - dns
