---
##############
#
# Extra variables need to be passed to this playbook at runtime to create the
# secret which will contain the keytab for the group sync authoprization operator
#
# centosci_ocp_api_token_stg
# centosci_ocp_api_host_stg
# env
#
##############


- name: Create openshift secret containing keytab
  hosts: localhost

  tasks:

    - name: Create the CentosCIAuthorization operator keytab k8s Secret staging
      community.okd.k8s:
        api_key: "{{ centosci_ocp_api_token_stg }}"
        host: "{{ centosci_ocp_api_host_stg }}"
        validate_certs: no
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "centos-ci-keytab-secret"
            namespace: "centos-ci-authorization-operator"
          data:
            centos-ci-authorization-keytab:
              "{{ centosci_authorization_keytab_file | b64encode }}"
      vars:
        centosci_authorization_keytab_file:
          "{{ lookup('file',
          '../pkistore/aws-ocp/centos-ci-authorization-operator-stg-keytab.kt')
          }}"
      tags:
        - deploy-operators
