---
# This ad-hoc playbook is written only to support Seamicro Chassis (now dead product)
# It uses some variables like user/pass to access Chassis rest API and configure/reset compute nodes
# By default, for CI purposes we are ensuring that we add a second path to chassis/fabric to present multipath and so increase available bandwdith during tests

- hosts: "{{ node_name }}"
  gather_facts: False
  become: True

# Some pre-defined list that will be added for 'uri' module and converted to json for rest api
  vars:
    seamicro_add_disk_body:
      value: "{{ seamicro_diskid }}"
      readonly: false
      username: "{{ seamicro_chassis_user }}"
      password: "{{ seamicro_chassis_pass }}"
    seamicro_reset_body:
      action: reset
      using-pxe: "true"
      username: "{{ seamicro_chassis_user }}"
      password: "{{ seamicro_chassis_pass }}"
    seamicro_poweroff_body:
      action: power-off
      force: "true"
      username: "{{ seamicro_chassis_user }}"
      password: "{{ seamicro_chassis_pass }}"


  tasks:
    - block:
      - name: Generate tftp config for Seamicro node
        template:
          src: pxeboot.j2
          dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ mac_address | lower | replace(':','-') }}"
          mode: 0755
        tags:
          - pxe
      - name: Generate kickstart file[s] for Seamicro node[s]  
        template: 
          src: "{{ item }}"
          dest: "/var/www/html/ks/{{ inventory_hostname }}-ks.cfg" 
          mode: 0755
        with_first_found:
          - "../templates/kickstarts/ci-centos-{{ centos_dist }}-ks.j2"
        tags:
          - pxe
          - ks
      delegate_to: "{{ deploy_node }}"

    - block:
      - name: Deleting additional path to the Seamicro node[s]
        uri: 
          url: "https://{{ seamicro_chassis }}.ci.centos.org/v2.0/server/{{ seamicro_srvid }}/vdisk/{{ seamicro_vdisk_slot }}?username={{ seamicro_chassis_user }}&password={{ seamicro_chassis_pass }}" 
          validate_certs: no
          method: DELETE
          status_code: 200,400
          timeout: 120

      - name: Wait for the disk to be removed
        uri: 
          url: "https://{{ seamicro_chassis }}.ci.centos.org/v2.0/server/{{ seamicro_srvid }}/vdisk/{{ seamicro_vdisk_slot }}?username={{ seamicro_chassis_user }}&password={{ seamicro_chassis_pass }}"
          validate_certs: no
          method: GET
          timeout: 120
          status_code: 200,201,404
        register: http_result
        until: http_result['status'] == 404
        retries: 5
        delay: 10 

      - name: Adding additional path to vdisk to the Seamicro node[s]
        uri:
          url: "https://{{ seamicro_chassis }}.ci.centos.org/v2.0/server/{{ seamicro_srvid }}/vdisk/{{ seamicro_vdisk_slot }}" 
          validate_certs: no
          method: PUT
          body_format: json
          body: "{{ seamicro_add_disk_body | to_json }}"
          status_code: 201
          timeout: 120

      - name: Resetting the Seamicro node[s]
        uri:
          url: "https://{{ seamicro_chassis }}.ci.centos.org/v2.0/server/{{ seamicro_srvid }}"
          validate_certs: no
          method: POST
          body_format: json
          body: "{{ seamicro_reset_body | to_json }}"
          timeout: 180
        tags: 
          - reset

      - name: Waiting for Seamicro node[s] to be available through ssh 
        wait_for:
          port: 22 
          host: "{{ inventory_hostname }}" 
          timeout: 1200

      - name: Sending back useful information for duffy provisioner
        set_fact:
          duffy_out:
            nodes:
              - hostname: "{{ node_name }}"
                ipaddr: "{{ ip }}"


      delegate_to: localhost


