---
- hosts: "{{ ipmi_target }}"
  vars_prompt:
    - name: "ipmi_target"
      prompt: "Host to reset through ipmi ? "
      private: no
  gather_facts: False

  tasks:
    - name: Resetting node through ipmi
      shell: ipmitool -H "{{ ipmi_ip }}" -U "{{ ipmi_user }}" -P "{{ ipmi_pass }}" -I lanplus chassis power reset
      delegate_to: "{{ ipmitool_host }}"
    
