---
- hosts: koji-builders
  become: True
  gather_facts: False

  pre_tasks:
    - name: removing versionlock plugin
      yum:
        name: "*"
        state: latest
        update_cache: True

  roles:
    - kojid

