---
- src: git+https://github.com/CentOS/ansible-role-ansible-host
  name: ansible-host
- src: git+https://github.com/CentOS/ansible-role-baseline
  name: baseline
- src: git+https://github.com/CentOS/ansible-role-centos-backup
  name: centos-backup
- src: git+https://github.com/CentOS/ansible-role-certbot
  name: certbot
- src: git+https://github.com/CentOS/ansible-role-haproxy
  name: haproxy
- src: git+https://github.com/CentOS/ansible-role-httpd
  name: httpd
- src: git+https://github.com/CentOS/ansible-role-iptables
  name: iptables
- src: git+https://github.com/CentOS/ansible-role-kojid
  name: kojid
- src: git+https://github.com/CentOS/ansible-role-mantisbt
  name: mantisbt
- src: git+https://github.com/CentOS/ansible-role-mysql
  name: mysql
- src: git+https://github.com/CentOS/ansible-role-pagure
  name: pagure
- src: git+https://github.com/CentOS/ansible-role-postfix
  name: postfix
- src: git+https://github.com/CentOS/ansible-role-repospanner
  name: repospanner
- src: git+https://github.com/CentOS/ansible-role-sshd
  name: sshd
- src: git+https://github.com/CentOS/ansible-role-zabbix-agent
  name: zabbix-agent
- src: git+https://github.com/CentOS/ansible-role-zabbix-server
  name: zabbix-server
